### ISSUE TITLE
Encountered an error during the first training session on D-Nerf dataset

### ISSUE THREAD

**Issue by HsiehTPE** [CVMI-Lab/SC-GS#19]
Dear devs,
  
After I configured the training environment as required, I used 

> **Train with terminal**

 for the first training(I have edited data path in the code): 
`# Train with terminal only (for the resolution of 400*400 with best PSNR)
CUDA_VISIBLE_DEVICES=0 python train_gui.py --source_path YOUR/PATH/TO/DATASET/jumpingjacks --model_path outputs/jumpingjacks --deform_type node --node_num 512 --hyper_dim 8 --is_blender --eval --gt_alpha_mask_as_scene_mask --local_frame --resolution 2 --W 800 --H 800`

But encountered the following error type:
![image](https://github.com/yihua7/SC-GS/assets/86395013/ab529864-e269-4863-ac4e-33bf76772706)

Below is the structure of the dataset I placed:
![image](https://github.com/yihua7/SC-GS/assets/86395013/3d314ae5-068b-420b-b664-729e235fd0c9)

Could you please help me identify the possible reasons for this error?
Thank you very much! Once again, thank you for your extraordinary work.

**Comment by yihua7** [comment]
Hi,
It's because the Gaussian rasterization lib you use is not exactly what we recommend in the readme file.

You can choose to reinstall the rasterizer using: `pip install ./submodules/diff-gaussian-rasterization` or remove the `alpha` in the code since your current version of the rasterizer seems to return three values `rendered_image, radii, depth` only.

**Comment by HsiehTPE** [comment]
It works, thanks for your reply!

Wish you have a good day : )
