### ISSUE TITLE
Training on static scenes

### ISSUE THREAD

**Issue by Lewis-lv0** [CVMI-Lab/SC-GS#33]
Hi @yihua7 , thanks for this great work. I have a question on training on static scenes. I wonder whether we can optimize the control points locations and the deformation MLP on a single static scene, since we don't have the motion supervision

I would appreciate if you could help me with this question :)

**Comment by yihua7** [comment]
Hi,
Of course, we can train SC-GS on static scenes. However, the control points are initialized by furthest sampling rather than optimized. Motion supervision is not necessary for editing, since the deformation graph can also be built by connecting neighboring control points. Demos of T&T scenes are shown in the gifs in Readme.
