### ISSUE TITLE
Results with ProgressiveBandFrequency

### ISSUE THREAD

**Issue by zhenyuan1234** [CVMI-Lab/SC-GS#47]
When I try to train with the ProgressiveBandFrequency function on D-Nerf dataset, the test results are very poor, what is the reason for this? Thank you!
![image](https://github.com/user-attachments/assets/5bf1a82e-0d2a-4089-bac5-7cdb8632d7dc)

**Comment by yihua7** [comment]
Hi,
Have you updated the frequency band of the mask at each iteration by invoking the update [func](https://github.com/yihua7/SC-GS/blob/26cd57d09598b2f5d951029808a5ac9f0ff4f626/utils/time_utils.py#L278C9-L278C20)?
Could you check the mask value during the test time?
Actually, it should perform the same as the [freq embedder](https://github.com/yihua7/SC-GS/blob/26cd57d09598b2f5d951029808a5ac9f0ff4f626/utils/time_utils.py#L226) when all bands are on. There seem to be some bugs in your experiments. The [progressive-banding option](https://github.com/yihua7/SC-GS/blob/26cd57d09598b2f5d951029808a5ac9f0ff4f626/utils/time_utils.py#L323C17-L323C39) is not turned on during our experiments but left in the code, it may cause some bugs due to the lack of code maintaining.

**Comment by zhenyuan1234** [comment]
Thanks for your kind reply. I made sure the mask was turned on by adding --progressive_brand_time to the training instruction. I also print the mask update process and it shows to be correct. It is worth noting that the validation metrics during training are also correct, but the metrics with python rander.py are very poor. Can you think of any reason for this, thanks!

**Comment by yihua7** [comment]
The problem may be the band is not all on during running the render.py, since the behavior of train.py seems normal.
Could you print the band mask during the rendering in render.py?

**Comment by zhenyuan1234** [comment]
Thank you for your sincere reply. I have another question. When training on the Lego dataset using the instructions you gave, the experimental results are not good (about 25.6 PSNR). What is the reason for this, thanks!

**Comment by yihua7** [comment]
Hi, please refer to the paper. Lego's train and test sets are inconsistent (the motion does not match).
