### ISSUE TITLE
请问这些数据不能创建model, 提示No good initial image pair found,数据要求是？

### ISSUE THREAD

**Issue by wing158** [CVMI-Lab/SC-GS#8]
![00000](https://github.com/yihua7/SC-GS/assets/29857187/cc5f176f-2d63-4112-a127-6e547abe2b96)
![00038](https://github.com/yihua7/SC-GS/assets/29857187/e5fc6166-0d7b-4973-8124-6e6673c3349a)
![00203](https://github.com/yihua7/SC-GS/assets/29857187/ea370d11-21d4-4cb4-a1c9-43a687ba78ce)
![image](https://github.com/yihua7/SC-GS/assets/29857187/006be1e0-be28-4168-9e90-bc6e6f185644)
720*800，

**Comment by yihua7** [comment]
Hello, here are some of my thoughts on your data:

1. I believe the problem occurred when you ran COLMAP. Your images actually have a fixed camera pose and white backgrounds, so the camera parameters cannot be estimated by multi-view stereo.

2. For this type of data, it lacks multi-view information. I hold that dynamic NeRF or dynamic Gaussians cannot be trained, which heavily rely on multi-view photometric consistency. 

3. I strongly suggest you to try those approaches utilizing human body priors, such as [Animatable Gaussians](https://animatable-gaussians.github.io/), [GaussianAvatar](https://huliangxiao.github.io/GaussianAvatar), and [3DGS-Avatar](https://neuralbodies.github.io/3DGS-Avatar/). Using SMPL model to represent human shapes and serve as a basis for dynamic deformation makes it possible to reconstruct such scenes. 

4. But I believe these approaches are still difficult on your data, since it seems to be generated by some diffusion model (e.g. AnimateAnyone) and temporal consistency is not promised.

**Comment by wing158** [comment]
已解决，用其他扣图软件完成绿幕图片保存并处理，可以完成colmap。
总结：对视频一定要求进行筛选，实现部分角度输出。
